parameters:
    data_source_file: 'https://data.binance.vision/data/spot/daily/klines/BTCUSDT/1m/BTCUSDT-1m-2023-01-05.zip'
    data_work_dir: '%empirica.project_dir%/var/binance'
    plot_file: '%empirica.project_dir%/qwe3.png'
    plot_font: '%empirica.project_dir%/vendor/zkrat/draw-ohlc/src/font/Hack-Regular.ttf'

services:
    _defaults:
    #    autowire: true
        autoconfigure: true
    data_symbol_base:
        class: EmpiricaPlatform\Terminal\ValueObject\Symbol
        factory: ['EmpiricaPlatform\Terminal\ValueObject\Symbol', 'from']
        arguments: ['BTC']
    data_symbol_quote:
        class: EmpiricaPlatform\Terminal\ValueObject\Symbol
        factory: ['EmpiricaPlatform\Terminal\ValueObject\Symbol', 'from']
        arguments: ['USDT']
    data_symbol_pair:
        class: EmpiricaPlatform\Terminal\ValueObject\SymbolPair
        arguments: ['@data_symbol_base', '@data_symbol_quote']
    data_iterator:
        public: true
        class: EmpiricaPlatform\PeriodicHistory\OhlcIterator
        arguments: ['@data_symbol_pair']
        #arguments: ['@data_symbol_pair', '%data_source_file%', '%data_work_dir%']

    EmpiricaPlatform\Terminal\DataProvider\HistoryDataProvider:
        autowire: true


    plot_list:
        class: EmpiricaPlatform\Plot\HistoryData\OhlcList
        factory: [ 'EmpiricaPlatform\Plot\HistoryData\OhlcList', 'create' ]
        arguments: [ 0 ]

    plot_canvas:
        class: EmpiricaPlatform\Plot\DrawImage\DrawCanvas
        factory: [ 'EmpiricaPlatform\Plot\DrawImage\DrawCanvas', 'createCanvas' ]
        arguments: [ 1000, 600 ]
        calls:
            - [ setFontPath, [ '%plot_font%' ] ]
            - [ setFontSize, [ 10 ] ]
    plot:
        autowire: true
        class: EmpiricaPlatform\Terminal\Output\ChartOutput
