services:
    # default configuration for services in *this* file
    #_defaults:
    #    autowire: true      # Automatically injects dependencies in your services.
    #    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    data_symbol_base:
        class: EmpiricaPlatform\Terminal\ValueObject\Symbol
        factory: ['EmpiricaPlatform\Terminal\ValueObject\Symbol', 'from']
        arguments: ['BTC']
    data_symbol_quote:
        class: EmpiricaPlatform\Terminal\ValueObject\Symbol
        factory: ['EmpiricaPlatform\Terminal\ValueObject\Symbol', 'from']
        arguments: ['USDT']
    data_symbol_pair:
        class: EmpiricaPlatform\Terminal\ValueObject\SymbolPair
        arguments: ['@data_symbol_base', '@data_symbol_quote']
    data_iterator:
        class: EmpiricaPlatform\PeriodicProvider\OhlcIterator
        arguments: ['@data_symbol_pair']
        #arguments: ['@data_symbol_pair', '%data_source_file%', '%data_work_dir%']
